
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'prod'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    
- script: 
    npm install
    npm run build-prod

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'angular-app'
  displayName: 'Publish Build Artifacts'
